project_id = "fakkzdfwpucpgndofgcu"

[functions.get-mapbox-token]
verify_jwt = false

[functions.get-properties]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.submit-contact]
verify_jwt = false
